name = "EAGO"
uuid = "bb8be931-2a91-5aca-9f87-79e1cb69959a"
authors = ["Matthew Wilhelm <matthew.wilhelm@uconn.edu>, Robert Gottlieb <robert.x.gottlieb@uconn.edu>, Dimitri Alston <dimitri.alston@uconn.edu>, Alireza Miraliakbar <alireza.miraliakbar@uconn.edu>, and Matthew Stuber <matthew.stuber@uconn.edu>"]
version = "0.8.4"

[deps]
Cassette = "7057c7e9-c182-5462-911a-8362d720325c"
Cbc = "9961bab8-2fa3-5c5a-9d89-47fab24efd76"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
FastRounding = "fa42c844-2597-5d31-933b-ebd51ab2693f"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
IntervalArithmetic = "d1acc4aa-44c8-5952-acd4-ba5d80a2a253"
IntervalContractors = "15111844-de3b-5229-b4ba-526f2f385dc9"
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MINLPTests = "ee0a3090-8ee9-5cdb-b8cb-8eeba3165522"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
McCormick = "53c679d3-6890-5091-8386-c291e8c8aaa1"
NaNMath = "77ba4419-2d1f-58cd-9bb1-8ffee604a2e3"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"

[compat]
Cassette = "0.3.1"
Cbc = "~1"
DataStructures = "~0.17, ~0.18"
DocStringExtensions = "~0.8, ~0.9"
FastRounding = "~0.2, ~0.3"
ForwardDiff = "~0.10"
IntervalArithmetic = "~0.20"
IntervalContractors = "~0.4"
Ipopt = "1.10"
JuMP = "1.12"
MINLPTests = "0.5.2"
MathOptInterface = "~1"
McCormick = "0.13"
NaNMath = "0.3.5, 1.0"
PrettyTables = "~2"
Reexport = "~0.2, ~1"
Requires = "~1"
SpecialFunctions = "~1, ~2"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
