name = "EAGO"
uuid = "bb8be931-2a91-5aca-9f87-79e1cb69959a"
version = "0.2.1"

[deps]
Calculus = "49dc2e85-a5d0-5ad3-a950-438e2897f1b9"
Cassette = "7057c7e9-c182-5462-911a-8362d720325c"
DiffRules = "b552c78f-8df3-52c6-915a-8e097449b14b"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
GLPK = "60bf3e95-4087-53dc-ae20-288a0d20c6a6"
IntervalArithmetic = "d1acc4aa-44c8-5952-acd4-ba5d80a2a253"
IntervalContractors = "15111844-de3b-5229-b4ba-526f2f385dc9"
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"


[compat]
Calculus = "≥ 0.4.1"
Cassette = "~0.2.1"
DiffRules = "≥ 0.0.5"
ForwardDiff = "≥ 0.10.1"
GLPK = "≥ 0.9.1"
IntervalArithmetic = "≥ 0.15"
IntervalContractors = "≥ 0.3"
Ipopt = "≥ 0.5.1"
JuMP = "~0.19.0"
MathOptInterface = "~0.8.1"
Reexport = "0.2.0"
StaticArrays = "~0.8.3"
julia = "1"

[extras]

[targets]
