name = "EAGO"
uuid = "bb8be931-2a91-5aca-9f87-79e1cb69959a"
authors = ["Matthew Wilhelm <matthew.wilhelm@uconn.edu>"]
version = "0.4.0"

[deps]
Cassette = "7057c7e9-c182-5462-911a-8362d720325c"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
GLPK = "60bf3e95-4087-53dc-ae20-288a0d20c6a6"
IntervalArithmetic = "d1acc4aa-44c8-5952-acd4-ba5d80a2a253"
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
McCormick = "53c679d3-6890-5091-8386-c291e8c8aaa1"
ReverseMcCormick = "f9d89e60-3bef-4186-aa8f-bdf0d7614dd6"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
NumericIO = "6c575b1c-77cb-5640-a5dc-a54116c90507"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
Cassette = "0.3.1"
DataStructures = "~0.17"
DocStringExtensions = "~0.8"
ForwardDiff = "~0.5.0, ~0.6, ~0.7, ~0.8, ~0.9, ~0.10"
GLPK = "~0.9, ~0.10, ~0.11, ~0.12"
IntervalArithmetic = "0.16.3, 0.16.4, 0.16.5, 0.16.6, 0.16.7"
Ipopt = "0.6.0, 0.6.1"
JuMP = "0.19.2, 0.20.0"
MathOptInterface = "0.8.1, 0.8.2, 0.8.3, 0.8.4, ~0.9"
McCormick = "~0.2"
ReverseMcCormick = "~0.2"
Reexport = "~0.2"
NumericIO = "= 0.3.1"
julia = "~1.2, ~1.3,~1.4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
